apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  zookeeper.properties: |
    dataDir=/opt/kafka_2.12-3.6.0/data/zookeeper
    clientPort=2181
    maxClientCnxns=0
    admin.enableServer=false
    # admin.serverPort=8080
